/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userInterface;

import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import org.json.simple.parser.ParseException;

import apiControler.ApiController;
import java.io.FileNotFoundException;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import org.json.simple.JSONArray;
import org.json.simple.JSONObject;

/**
 *
 * @author Parinda
 */
public class LogIn extends javax.swing.JFrame {

    private final JFileChooser files = new JFileChooser();
    private File uploadFile;
    private ApiController controller = new ApiController();
    private String id = null, name = null, email = null;
    private int fo_code;
    
    /**
     * Creates new form LogIn
     */
    public LogIn() {
        initComponents();
        files.setCurrentDirectory(new File("Documents"));
    }
    
    public void openPanel(JPanel panel){
        container.removeAll();
        container.repaint();
        container.revalidate();
        container.add(panel);
        container.repaint();
        container.revalidate();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        container = new javax.swing.JPanel();
        logIn = new javax.swing.JPanel();
        logIn_userName = new javax.swing.JTextField();
        logIn_passWord = new javax.swing.JTextField();
        logIn_btn = new javax.swing.JButton();
        logIn_forgot = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        logIn_create = new javax.swing.JLabel();
        reg = new javax.swing.JPanel();
        reg_userName = new javax.swing.JTextField();
        reg_email = new javax.swing.JTextField();
        reg_passWord = new javax.swing.JTextField();
        reg_conPassWord = new javax.swing.JTextField();
        reg_Submit = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        profile = new javax.swing.JPanel();
        profile_Upload = new javax.swing.JButton();
        profile_Name = new javax.swing.JLabel();
        profile_Email = new javax.swing.JLabel();
        profile_Download = new javax.swing.JButton();
        profile_LogOut = new javax.swing.JButton();
        forgotPass = new javax.swing.JPanel();
        forgot_NewPass = new javax.swing.JTextField();
        forgot_ConNewPass = new javax.swing.JTextField();
        forgot_change = new javax.swing.JButton();
        forgot_email = new javax.swing.JTextField();
        forgot_send = new javax.swing.JButton();
        forgot_code = new javax.swing.JTextField();
        forgot_check = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        forgotPass_Back = new javax.swing.JButton();
        upload = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        upload_filename = new javax.swing.JLabel();
        download = new javax.swing.JPanel();
        download_ListPanel = new javax.swing.JScrollPane();
        download_List = new javax.swing.JList<>();
        download_back = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        container.setLayout(new java.awt.CardLayout());

        logIn_btn.setText("Log In");
        logIn_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logIn_btnActionPerformed(evt);
            }
        });

        logIn_forgot.setText("Forgot Password?");
        logIn_forgot.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logIn_forgotMouseClicked(evt);
            }
        });

        jLabel5.setText("Email");

        jLabel6.setText("Password");

        logIn_create.setText("Create a Account");
        logIn_create.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logIn_createMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout logInLayout = new javax.swing.GroupLayout(logIn);
        logIn.setLayout(logInLayout);
        logInLayout.setHorizontalGroup(
            logInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(logInLayout.createSequentialGroup()
                .addContainerGap(134, Short.MAX_VALUE)
                .addGroup(logInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(logInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(logIn_passWord, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(logIn_userName, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel5)
                        .addComponent(jLabel6)
                        .addGroup(logInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(logIn_create, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(logIn_forgot, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(logIn_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(135, Short.MAX_VALUE))
        );
        logInLayout.setVerticalGroup(
            logInLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(logInLayout.createSequentialGroup()
                .addContainerGap(175, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(logIn_userName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(logIn_passWord, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(logIn_btn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(logIn_forgot)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(logIn_create)
                .addContainerGap(178, Short.MAX_VALUE))
        );

        container.add(logIn, "card2");

        reg.setPreferredSize(new java.awt.Dimension(486, 519));

        reg_Submit.setText("Submit");
        reg_Submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reg_SubmitActionPerformed(evt);
            }
        });

        jLabel7.setText("Name");

        jLabel8.setText("Email");

        jLabel9.setText("Password");

        jLabel10.setText("Conform Password");

        javax.swing.GroupLayout regLayout = new javax.swing.GroupLayout(reg);
        reg.setLayout(regLayout);
        regLayout.setHorizontalGroup(
            regLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(regLayout.createSequentialGroup()
                .addContainerGap(134, Short.MAX_VALUE)
                .addGroup(regLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(jLabel9)
                    .addComponent(jLabel8)
                    .addComponent(jLabel7)
                    .addGroup(regLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(reg_conPassWord, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(reg_passWord, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(reg_email, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(reg_userName, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(reg_Submit, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(135, Short.MAX_VALUE))
        );
        regLayout.setVerticalGroup(
            regLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(regLayout.createSequentialGroup()
                .addContainerGap(92, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(reg_userName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(reg_email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(reg_passWord, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(reg_conPassWord, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(reg_Submit)
                .addContainerGap(203, Short.MAX_VALUE))
        );

        container.add(reg, "card2");

        profile.setPreferredSize(new java.awt.Dimension(486, 519));

        profile_Upload.setText("Upload");
        profile_Upload.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                profile_UploadActionPerformed(evt);
            }
        });

        profile_Name.setText("Name");

        profile_Email.setText("Email");

        profile_Download.setText("Download");
        profile_Download.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                profile_DownloadActionPerformed(evt);
            }
        });

        profile_LogOut.setText("LogOut");
        profile_LogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                profile_LogOutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout profileLayout = new javax.swing.GroupLayout(profile);
        profile.setLayout(profileLayout);
        profileLayout.setHorizontalGroup(
            profileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(profileLayout.createSequentialGroup()
                .addContainerGap(107, Short.MAX_VALUE)
                .addGroup(profileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(profileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(profile_Name, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(profile_Email, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(profile_LogOut, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(profileLayout.createSequentialGroup()
                        .addComponent(profile_Upload, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(profile_Download, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(134, Short.MAX_VALUE))
        );
        profileLayout.setVerticalGroup(
            profileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(profileLayout.createSequentialGroup()
                .addContainerGap(195, Short.MAX_VALUE)
                .addComponent(profile_Name)
                .addGap(30, 30, 30)
                .addComponent(profile_Email)
                .addGap(30, 30, 30)
                .addGroup(profileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(profile_Upload)
                    .addComponent(profile_Download))
                .addGap(47, 47, 47)
                .addComponent(profile_LogOut)
                .addContainerGap(143, Short.MAX_VALUE))
        );

        container.add(profile, "card2");

        forgot_NewPass.setToolTipText("test");
        forgot_NewPass.setEnabled(false);

        forgot_ConNewPass.setToolTipText("fgdfgdfgfgfdg");
        forgot_ConNewPass.setEnabled(false);

        forgot_change.setText("Change Password");
        forgot_change.setEnabled(false);
        forgot_change.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                forgot_changeActionPerformed(evt);
            }
        });

        forgot_send.setText("Send");
        forgot_send.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                forgot_sendActionPerformed(evt);
            }
        });

        forgot_code.setEnabled(false);

        forgot_check.setText("Check");
        forgot_check.setEnabled(false);
        forgot_check.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                forgot_checkActionPerformed(evt);
            }
        });

        jLabel1.setText("Enter your email Address");

        jLabel2.setText("Enter Code we send to your Email");

        jLabel3.setText("New Password");

        jLabel4.setText("Conform New Password");

        forgotPass_Back.setText("Back");
        forgotPass_Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                forgotPass_BackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout forgotPassLayout = new javax.swing.GroupLayout(forgotPass);
        forgotPass.setLayout(forgotPassLayout);
        forgotPassLayout.setHorizontalGroup(
            forgotPassLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(forgotPassLayout.createSequentialGroup()
                .addContainerGap(131, Short.MAX_VALUE)
                .addGroup(forgotPassLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(forgot_change, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(forgotPassLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(forgot_ConNewPass, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(forgot_NewPass, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(forgotPassLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(forgot_send, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(forgot_email, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(forgotPassLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(forgot_check, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(forgot_code, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jLabel1)
                        .addComponent(jLabel2)
                        .addComponent(jLabel3)
                        .addComponent(jLabel4))
                    .addComponent(forgotPass_Back, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(138, Short.MAX_VALUE))
        );
        forgotPassLayout.setVerticalGroup(
            forgotPassLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, forgotPassLayout.createSequentialGroup()
                .addContainerGap(91, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(forgot_email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(forgot_send)
                .addGap(39, 39, 39)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(forgot_code, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(forgot_check)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(forgot_NewPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(forgot_ConNewPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(forgot_change)
                .addGap(35, 35, 35)
                .addComponent(forgotPass_Back)
                .addContainerGap(47, Short.MAX_VALUE))
        );

        container.add(forgotPass, "card2");

        jButton1.setText("Open");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Upload");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Back");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout uploadLayout = new javax.swing.GroupLayout(upload);
        upload.setLayout(uploadLayout);
        uploadLayout.setHorizontalGroup(
            uploadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(uploadLayout.createSequentialGroup()
                .addContainerGap(31, Short.MAX_VALUE)
                .addGroup(uploadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(uploadLayout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(upload_filename, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(uploadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jButton3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 81, Short.MAX_VALUE)))
                .addContainerGap(64, Short.MAX_VALUE))
        );
        uploadLayout.setVerticalGroup(
            uploadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(uploadLayout.createSequentialGroup()
                .addContainerGap(226, Short.MAX_VALUE)
                .addGroup(uploadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(upload_filename, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton2)
                .addGap(25, 25, 25)
                .addComponent(jButton3)
                .addContainerGap(188, Short.MAX_VALUE))
        );

        container.add(upload, "card2");

        download.setPreferredSize(new java.awt.Dimension(486, 519));

        download_List.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 20));
        download_List.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5", "Item 5", "Item 5", "Item 5", "Item 5", "Item 5", "Item 5", "Item 5", "Item 5", "Item 5", "Item 5", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        download_List.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        download_List.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        download_List.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                download_ListMouseClicked(evt);
            }
        });
        download_ListPanel.setViewportView(download_List);

        download_back.setText("Back");

        jLabel11.setText("Click On Your Choosed File");

        javax.swing.GroupLayout downloadLayout = new javax.swing.GroupLayout(download);
        download.setLayout(downloadLayout);
        downloadLayout.setHorizontalGroup(
            downloadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(downloadLayout.createSequentialGroup()
                .addContainerGap(83, Short.MAX_VALUE)
                .addGroup(downloadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(download_ListPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(download_back, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(98, Short.MAX_VALUE))
        );
        downloadLayout.setVerticalGroup(
            downloadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(downloadLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel11)
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(download_ListPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 431, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(download_back)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        container.add(download, "card2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(container, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(container, javax.swing.GroupLayout.PREFERRED_SIZE, 519, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void download_ListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_download_ListMouseClicked
        int buttunNum = JOptionPane.showConfirmDialog(rootPane, download_List.getSelectedValue(),"Do You want to Download this file?",JOptionPane.YES_NO_OPTION);
        if(buttunNum == JOptionPane.YES_OPTION){
            ApiController control = new ApiController();
            try {
                control.downLoad(id, download_List.getSelectedValue());
                JOptionPane.showMessageDialog(rootPane, "Download Finished!");
            } catch (FileNotFoundException ex) {
                Logger.getLogger(LogIn.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(rootPane, "Sorry, This file is not exist in your cloud space ");
            } catch (IOException ex) {
                Logger.getLogger(LogIn.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_download_ListMouseClicked

    private void logIn_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logIn_btnActionPerformed
        try {
            JSONArray infoArray = controller.GETRequest("/user/one/email/"+logIn_userName.getText().trim());
            System.out.print(infoArray);
            JSONObject info = (JSONObject) infoArray.get(0);
            int res = 200;
            if(info.get("description") != null){
                res = (int) info.get("description");
            }
            if(res > 200){
                JOptionPane.showMessageDialog(rootPane, "This name or Email is not exist");
            }else{
                if(info.get("password").equals( logIn_passWord.getText().trim())){
                    id = String.valueOf(info.get("id"));
                    name = (String) info.get("name");
                    email = (String) info.get("email");
                    profile_Name.setText(info.get("name").toString());
                    profile_Email.setText(info.get("email").toString());
                    openPanel(profile);
                }else{
                    JOptionPane.showMessageDialog(rootPane, "Incorect Password!");
                }
            }
        } catch (IOException | ParseException ex) {
            Logger.getLogger(LogIn.class.getName()).log(Level.SEVERE, null, ex);
            System.out.print("parinda :"+ex.getMessage());
        }
    }//GEN-LAST:event_logIn_btnActionPerformed

    private void logIn_forgotMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logIn_forgotMouseClicked
        openPanel(forgotPass);
    }//GEN-LAST:event_logIn_forgotMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int returnVal = files.showOpenDialog(this);
        if(returnVal == JFileChooser.APPROVE_OPTION){
            uploadFile = files.getSelectedFile();
            upload_filename.setText(uploadFile.getName());
        }else{
            upload_filename.setText("file choose eror : "+returnVal);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        ApiController api = new ApiController();
        try {
            System.out.println(api.POSTImageRequest("/user/files/"+id, uploadFile));
            uploadFile = null;
            upload_filename.setText("");
        } catch (IOException | ParseException ex) {
            Logger.getLogger(LogIn.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void logIn_createMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logIn_createMouseClicked
        openPanel(reg);
    }//GEN-LAST:event_logIn_createMouseClicked

    private void profile_UploadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_profile_UploadActionPerformed
        openPanel(upload);
    }//GEN-LAST:event_profile_UploadActionPerformed

    private void profile_DownloadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_profile_DownloadActionPerformed

        DefaultListModel list = new DefaultListModel();
        //String [] nameArray = {"kjhkhkjh","Bootstrap Sinhala Tutorial - Modal_10`~!@$%^&()_+=-,.';[{]}.mp4","Man_Magemada_(Hitha_Hangala_Nawathila)_Chamika_Sirimanna_Sinhalasongs.lk.mp3"};
        JSONArray listJson = null;
        try {
            listJson = controller.GETRequest("/user/files/"+id);
        } catch (IOException | ParseException ex) {
            Logger.getLogger(LogIn.class.getName()).log(Level.SEVERE, null, ex);
        }
        for(Object info : listJson){
            JSONObject temp = (JSONObject) info;
            list.addElement(temp.get("file_name").toString());
        }
        download_List.setModel(list);
        openPanel(download);
    }//GEN-LAST:event_profile_DownloadActionPerformed

    private void profile_LogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_profile_LogOutActionPerformed
        id = null; name = null; email = null;
        openPanel(logIn);
    }//GEN-LAST:event_profile_LogOutActionPerformed

    private void reg_SubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reg_SubmitActionPerformed
        if(!reg_userName.getText().isEmpty()){
            if(!reg_email.getText().isEmpty()){
                if(!reg_passWord.getText().isEmpty()){
                    if(!reg_conPassWord.getText().isEmpty()){
                        if(reg_passWord.getText().equals(reg_conPassWord.getText())){
                            JSONObject json = new JSONObject();
                            json.put("name", reg_userName.getText());
                            json.put("password",reg_passWord.getText());
                            json.put("email",reg_email.getText());
                            try {
                                JSONObject json2 = controller.POSTRequest("/user", json);
                                System.out.print("test : "+json2);
                                if((String)json2.get("description") != null && (int) json2.get("description") > 200){
                                    JOptionPane.showMessageDialog(rootPane, "Some Error. Please Try Again");
                                }else{
                                    openPanel(logIn);
                                }
                            } catch (IOException | ParseException ex) {
                                Logger.getLogger(LogIn.class.getName()).log(Level.SEVERE, null, ex);
                            }
                        }else{
                            JOptionPane.showMessageDialog(rootPane, "Passwords are not Same!");
                        }
                    }
                }
            }
        }
    }//GEN-LAST:event_reg_SubmitActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        openPanel(profile);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void forgot_sendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_forgot_sendActionPerformed
        EmailSender sendMail = new EmailSender();
        if(!forgot_email.getText().isEmpty()){
            JSONObject json = sendMail.sendEmail(forgot_email.getText());
            if((int) json.get("code") > 0){
                forgot_email.setEnabled(false);
                forgot_send.setEnabled(false);
                forgot_code.setEnabled(true);
                forgot_check.setEnabled(true);
                fo_code = (int) json.get("code");
            }else{
                System.out.println(json);
                JOptionPane.showMessageDialog(rootPane, "Please Check your email and Internet Connection. Email is not send!");
            }
        }else{
            JOptionPane.showMessageDialog(rootPane, "Please Enter your email");
        }
    }//GEN-LAST:event_forgot_sendActionPerformed

    private void forgot_checkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_forgot_checkActionPerformed
        if(fo_code == Integer.valueOf(forgot_code.getText())){
            forgot_NewPass.setEnabled(true);
            forgot_ConNewPass.setEnabled(true);
            forgot_change.setEnabled(true);
            forgot_code.setEnabled(false);
            forgot_check.setEnabled(false);
        }
    }//GEN-LAST:event_forgot_checkActionPerformed

    private void forgotPass_BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_forgotPass_BackActionPerformed
        openPanel(logIn);
    }//GEN-LAST:event_forgotPass_BackActionPerformed

    private void forgot_changeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_forgot_changeActionPerformed
        
    }//GEN-LAST:event_forgot_changeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LogIn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LogIn().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel container;
    private javax.swing.JPanel download;
    private javax.swing.JList<String> download_List;
    private javax.swing.JScrollPane download_ListPanel;
    private javax.swing.JButton download_back;
    private javax.swing.JPanel forgotPass;
    private javax.swing.JButton forgotPass_Back;
    private javax.swing.JTextField forgot_ConNewPass;
    private javax.swing.JTextField forgot_NewPass;
    private javax.swing.JButton forgot_change;
    private javax.swing.JButton forgot_check;
    private javax.swing.JTextField forgot_code;
    private javax.swing.JTextField forgot_email;
    private javax.swing.JButton forgot_send;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel logIn;
    private javax.swing.JButton logIn_btn;
    private javax.swing.JLabel logIn_create;
    private javax.swing.JLabel logIn_forgot;
    private javax.swing.JTextField logIn_passWord;
    private javax.swing.JTextField logIn_userName;
    private javax.swing.JPanel profile;
    private javax.swing.JButton profile_Download;
    private javax.swing.JLabel profile_Email;
    private javax.swing.JButton profile_LogOut;
    private javax.swing.JLabel profile_Name;
    private javax.swing.JButton profile_Upload;
    private javax.swing.JPanel reg;
    private javax.swing.JButton reg_Submit;
    private javax.swing.JTextField reg_conPassWord;
    private javax.swing.JTextField reg_email;
    private javax.swing.JTextField reg_passWord;
    private javax.swing.JTextField reg_userName;
    private javax.swing.JPanel upload;
    private javax.swing.JLabel upload_filename;
    // End of variables declaration//GEN-END:variables


/*
    public static void POSTRequest() throws IOException {
        
        JSONObject json = new JSONObject();
        json.put("name", "student");
        json.put("description", "student");
        final String POST_PARAMS = json.toJSONString();
        System.out.println(json);
        URL obj = new URL("http://localhost:8080/list");
        HttpURLConnection postConnection = (HttpURLConnection) obj.openConnection();
        postConnection.setRequestMethod("POST");
        //postConnection.setRequestProperty("userId", "a1bcdefgh");
        postConnection.setRequestProperty("Content-Type", "application/json");
        postConnection.setDoOutput(true);
        try (OutputStream os = postConnection.getOutputStream()) {
            os.write(POST_PARAMS.getBytes());
            os.flush();
            int responseCode = postConnection.getResponseCode();
            System.out.println("POST Response Code :  " + responseCode);
            System.out.println("POST Response Message : " + postConnection.getResponseMessage());
            if (responseCode == HttpURLConnection.HTTP_OK) {
                StringBuffer response;
                try (BufferedReader in = new BufferedReader(new InputStreamReader(postConnection.getInputStream()))) {
                    String inputLine;
                    response = new StringBuffer();
                    while ((inputLine = in .readLine()) != null) {
                        response.append(inputLine);
                    }
                }
                // print result
                System.out.println(response.toString());
            } else {
                System.out.println("POST NOT WORKED");
            }
        }
        
    }
    
    public static void MyGETRequest() throws IOException, ParseException {
        URL urlForGetRequest = new URL("http://localhost:8080/list");
        String readLine = null;
        HttpURLConnection conection = (HttpURLConnection) urlForGetRequest.openConnection();
        conection.setRequestMethod("GET");
        //conection.setRequestProperty("userId", "a1bcdef"); // set userId its a sample here
        conection.setRequestProperty("Content-Type", "application/json");
        int responseCode = conection.getResponseCode();
        if (responseCode == HttpURLConnection.HTTP_OK) {
            StringBuffer response;
            System.out.println("JSON String Result22222 " + conection.getInputStream());
            try (BufferedReader in = new BufferedReader(
                    new InputStreamReader(conection.getInputStream()))) {
                response = new StringBuffer();
                while ((readLine = in .readLine()) != null) {
                    response.append(readLine);
                }
            }
            
            // print result
            System.out.println("JSON String Result " + response.toString());
            JSONParser parser = new JSONParser();
            JSONArray jsonArray = (JSONArray) parser.parse(response.toString());
            JSONObject json = (JSONObject) jsonArray.get(0);
            System.out.println(json.get("name"));
        } else {
            System.out.println("GET NOT WORKED");
        }
    }
    */

}
